name: Android Release CI

on:
  release:
    types: [published]

env:
  KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
  KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
  HOST: ${{ secrets.HOST }}
  BEARER: ${{ secrets.BEARER }}
  GOOGLE_PLAY_SERVICE_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_JSON }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '17'

      - uses: actions/cache@v6
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', 'gradle/libs.versions.toml', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Build
        run: ./gradlew bundleRelease

      - name: Set publisher files
        run: echo $GOOGLE_PLAY_SERVICE_JSON | base64 -d > google-play-service.json

      - name: Run Release
        run: ./gradlew publishBundle

      - name: Notify Slack
        uses: slackapi/slack-github-action@v4.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "DAIgoAPP release: ${{ job.status }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        if: always()
